/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuildList: typeof import('./../src/components/virtual-list/src/builders/build-list.ts')['default']
    Defaults: typeof import('./../src/components/virtual-list/src/defaults.ts')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FixedSizeList: typeof import('./../src/components/virtual-list/src/components/fixed-size-list.ts')['default']
    Props: typeof import('./../src/components/virtual-list/src/props.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tree: typeof import('./../src/components/tree/src/tree.vue')['default']
    Types: typeof import('./../src/components/tree/src/types.ts')['default']
    UseTree: typeof import('./../src/components/tree/src/composables/useTree.ts')['default']
    VirtualList: typeof import('./../src/components/virtual-list/index.ts')['default']
    VirtualTree: typeof import('./../src/components/tree/src/virtual-tree.ts')['default']
  }
}
